### ISSUE TITLE
Output parsing

### ISSUE THREAD

**Issue by TMLutas** [5he11/RelexDistributor#2]
This is line 83:
Console.Write("Sending {0} Relex tokens to {1}... ", amount, to);

But the CSV has the first column being addresses and the second column being amounts so shouldn't it be
Console.Write("Sending {1} Relex tokens to {0}... ", amount, to);

**Comment by 5he11** [comment]
I think it's quite right to say "Sending 123.456 Relex tokens to 0x123456789abcdef", isn't it?

**Comment by TMLutas** [comment]
Oh good Lord, I had a brain malfunction. you're right.
